name: 8AM_Market_Update
on:
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Firebase
        run: pip install firebase-admin
      - name: Run Robot
        run: python bot.py
